### ISSUE TITLE
FR: Section Named Default Tab

### ISSUE THREAD

**Issue by chasegiunta** [studioespresso/craft3-defaulttab#5]
99% of the time, the first tab I'm creating is actually just the name of the section. Could this be implemented some how? I'm wondering if the broader implementation would be to allow the default tab setting input to allow twig or Craft's shortcut syntax, so one could just enter `{object.name}` (or similar)

**Comment by janhenckens** [comment]
Neat idea, thanks for the suggestion! 

Just this in 1.3.0, along with a small fix to make the plugin work for single sections again.
Should be in the store soon.
